[package]
name = "adder"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ckt-fmtv5-types.workspace = true
monoio.workspace = true

[[bin]]
name = "adder"
path = "src/main.rs"

[lints]
workspace = true
