[package]
name = "garbletest"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake3 = "1.8.2"
ckt = { version = "0.1.0", path = "../.." }
gobble = { version = "0.1.0", path = "../../gobble" }
monoio = "0.2.4"
